name: Data Processing and Testing

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-node-app .

    - name: Run Docker container in detached mode with custom command
      run: docker run -d --name data-processing-container my-node-app tail -f /dev/null

    - name: Check container status
      run: docker ps -a

    - name: Wait for the container to be ready
      run: |
        sleep 10
        docker logs data-processing-container

    - name: Run tests
      run: docker exec data-processing-container npm test

    - name: Cleanup
      run: docker rm -f data-processing-container
