name: Run application and update branch with new CSVs
on:
  push:
    tags: ['github-actions-run-app-dev-*']
jobs:
  checkout-data:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v4
      - name: ls
        run: cat ./data/products.csv
      - name: Upload data/ dir to artifact registry
        uses: actions/upload-artifact@v4
        with:
          name: data-tmp-${{ github.run_id }}
          path: ./data
  run:
    needs: [ checkout-data ]
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.DOCKER_REGISTRY }}/${{ github.repository }}-${{ vars.PACKAGE_NAME }}:development
    defaults:
      run:
        working-directory: /usr/csv-parser
    steps:
      - name: Download data/ dir from registry
        uses: actions/download-artifact@v4
        with:
          name: data-tmp-${{ github.run_id }}
          path: /usr/csv-parser/data
      - name: cat
        run: cat /usr/csv-parser/data/products.csv
      - name: Generate final data
        run: yarn start:github-actions
      - name: Archive final data to artifact registry
        uses: actions/upload-artifact@v4
        with:
          name: data-final-${{ github.run_id }}
          path: /usr/csv-parser/data/
  push-to-repo:
    needs: [ run ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.TARGET_BRANCH }}
      - name: Download final data from registry
        uses: actions/download-artifact@v4
        with:
          name: data-final-${{ github.run_id }}
          path: ./data
      - name: Push files
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m 'Autogenerated by Github Actions' || true
          git push origin ${{ vars.TARGET_BRANCH }}
